version: "3"
services:
  # frontend:
    # build: ./docker/front
    # networks:
    #   - frontend
    # image: burakhanaksoy/frontend:15.2
    # ports:
    #   - 8080:8080
  backend:
    image: burakhanaksoy/backend:15.1
    # build: ./docker/back
    # networks:
    #   - frontend
    #   - backend
    ports:
      - 8000:8000
  mongodb:
    image: mongo
    # networks:
    #   - backend
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    # networks:
    #   - backend
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo-data:
    driver: local

# networks:
#   frontend:
#     name: frontend
#     driver: bridge
#   backend:
#     name: backend
#     driver: bridge
